version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      replicas: 1

  auth:
    image: cyberadvance/authen-service
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/auth
    deploy:
      replicas: 1

  products:
    image: cyberadvance/rabu-products-api
    ports: 
      - "3002:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/products
    deploy:
      replicas: 1

  web:
    image: cyberadvance/rabu-gateway-apis
    ports: 
      - "80:80"
    depends_on:
      - auth
      - products
    deploy:
      replicas: 1